[package]
name = "client"
version = "0.1.0"
authors = ["Cassy343 <isilversmith810@gmail.com>"]
edition = "2018"


[dependencies]
common = {path = "../common"}
serde = "1.0"
js-sys = "0.3.48"
wasm-bindgen = { version = "0.2.71", features = ["nightly"] }
wee_alloc = "0.4.5"

[dependencies.web-sys]
version = "0.3.48"
features = [
    "WebSocket",
    "console",
    "MessageEvent",
    "CloseEvent",
    "ErrorEvent"
]

[lib]
crate-type =["cdylib"]