[package]
name = "client"
version = "0.1.0"
authors = ["Cassy343 <isilversmith810@gmail.com>"]
edition = "2018"


[dependencies]
wasm-bindgen = { version = "0.2.71", features = ["nightly"] }
web-sys = { version = "0.3.48", features = ["WebSocket", "console", "MessageEvent"] }

[lib]
crate-type =["cdylib"]