[package]
name = "client"
version = "0.1.0"
authors = ["Cassy343 <isilversmith810@gmail.com>"]
edition = "2018"


[dependencies]
common = {path = "../common"}
serde = "1.0"
js-sys = "0.3.48"
wasm-bindgen = { version = "0.2.71", features = ["nightly"] }
nalgebra = "0.25.3"

[lib]
crate-type =["cdylib"]

[dependencies.web-sys]
version = "0.3.48"
features = [
    'Document',
    'Element',
    'HtmlCanvasElement',
    'WebGlBuffer',
    'WebGlRenderingContext',
    'WebGlProgram',
    'WebGlShader',
    'Window',
    'WebSocket',
    'console',
    'MessageEvent',
    'WebGlUniformLocation',
    "CloseEvent",
    "ErrorEvent"
]
