[package]
name = "server"
version = "0.1.0"
authors = ["Cassy343 <isilversmith810@gmail.com>", "Maddymakesgames <madelinemakesgames@gmail.com>"]
edition = "2018"

[dependencies]
common = {path = "../common"}
serde_json = "1"
rand = "0.8.3"
futures = "0.3.13"
tokio = { version = "1.3.0", features = ["full"] }
warp = "0.3.0"
zip = "0.5.11"

[build-dependencies]
walkdir = "2.3.1"
zip = "0.5.11"
