[package]
name = "server"
version = "0.1.0"
authors = ["Cassy343 <isilversmith810@gmail.com>", "Maddymakesgames <madelinemakesgames@gmail.com>"]
edition = "2018"

[dependencies]
common = {path = "../common"}
serde_json = "1"
rand = "0.8.3"